{% set version = "0.0.5" %}

package:
  name: datapkg
  version: {{ version }}

source:
  path: ../../

build:
  script: python setup.py install
  number: 0
  entry_points:
    - datapkg = datapkg.__main__:main

requirements:
  build:
    # Basic
    - python
  run:
    # Basic
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    - paramiko
    - biopython
    - retrying
    - psutil
    # Scientific
    - numpy
    - scipy
    - pandas
    - scikit-learn
    # Database clients
    - sqlalchemy
    - mysqlclient
    - psycopg2
    # Binaries
    - p7zip
    - mariadb-server

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - flake8
  imports:
    - datapkg
  commands:
    - datapkg --help
    - datapkg file2db --help

about:
  home: http://kimlaborg.github.io/datapkg
  license: MIT
  summary: Helpful bioinformatics scripts.
