{% set version = "0.0.1" %}

package:
  name: datapkg
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  entry_points:
    - datapkg = datapkg.__main__:main

requirements:
  build:
    # Basic python
    - python
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    - paramiko
    - biopython
    - retrying
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    # Database
    - sqlalchemy
    - mysqlclient
    - psycopg2
    # System tools
    - p7zip

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
  imports:
    - datapkg
  commands:
    - datapkg --help
    - datapkg file2db --help

about:
  home: http://ostrokach.github.io/datapkg
  license: MIT
  summary: Helpful bioinformatics scripts.
