{% set data = load_setup_py_data() %}

package:
  name: odbo
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0
  entry_points:
    - odbo = odbo.__main__:main

requirements:
  build:
    # Basic
    - python
  run:
    # Basic
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    - paramiko
    - retrying
    - psutil
    # Scientific
    - numpy
    - scipy
    - pandas
    - scikit-learn
    # Database clients
    - mysql
    - mysqlclient
    - sqlalchemy
    # Binaries
    - p7zip
    # Kimlab
    - kmbio
    - kmtools >=0.0.16

test:
  imports:
    - odbo
  commands:
    - odbo --help
    - odbo file2db --help

about:
  home: http://kimlaborg.github.io/odbo
  license: MIT
  summary: Start and interact with databases through Python / Pandas.
